theme: jekyll-theme-architect
title: klasycznienielogiczny
subtitle: Zdrowia życzę!
locale: pl_PL
author: Piotr Paluch (klasycznienielogiczny)
date: 18.11.2020
email: piotr.pal98@gmail.com
keywords: github, AGH, test
show_downloads: true
description: Klasycznie sympatyczny. Po prostu
